import Head from "next/head"
import './page.css'

export const metadata = {
    title: 'Fight',
    description: 'Generated by create next app',
}


const FightPage = () => {

    return (
        <>
            <Head>
                <title>Fight</title>
                <meta name="description" content="Fight" />
                <link rel="icon" href="/favicon.ico" />
            </Head>,

            <div className="Header">

            </div>

            <div className="content">
                <div className="my-pokemon">
                    <div className="Bar">
                        <div className="name">
                            <img src="" alt="" id="my-pokemon-img"/>
                                <p id="my-pokemon-name"></p>
                        </div>
                        <div className="hp">
                            <div>Current HP:</div><div className="sec-brd"><div id="hp-line-my" className="hp-line"></div></div>
                            <p>
                                <span id="hp-count-my-current"></span>
                                /
                                <span id="hp-count-my"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div className="fight">
                    <input type="text" id="fight-input" placeholder="Enter your move here"/>
                        <div className="fight-btn">
                            <button className="btn-attack" id="fight-btn" disabled>FIGHT</button>
                        </div>
                        <textarea className="fight-log" readOnly id="fight-log">

                        </textarea>
                </div>
                <div className="enemy-pokemon">
                    <div className="Bar">
                        <div className="name">
                            <img src="" alt="" id="enemy-pokemon-img"/>
                                <p id="enemy-pokemon-name"></p>
                        </div>
                        <div className="hp">
                            <div>Current HP:</div><div id="hp-line-enemy" className="hp-line"></div>
                            <p>
                                <span id="hp-count-enemy-current"></span>
                                /
                                <span id="hp-count-enemy"></span>
                            </p>

                        </div>
                    </div>
                </div>
            </div>

            <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                <aside>
                    <p>Выполнил: Друганов А.В.</p>
                </aside>
            </footer>

        </>
    )
}

export default FightPage